# TODO: Run tests against database instance. DB2 is currently not supported by TravisCI out of the box
# Best thing to do would be to use a docker container for the database and run the tests against that.

language: node_js
dist: focal
sudo: required

cache:
  directories:
    - "node_modules"

matrix:
  fast_finish: true
  include:
    - node_js: "20"
    - node_js: "18"
    - node_js: "16"
    - node_js: "14"
install:
  - npm i

script:
  - npm run lint
  - npm run test-latest-knex
  - npm run test-min-knex

notifications:
  email: true
